stages:
  - container
  - assemble

.updateContainerJob:
  image: docker:stable
  stage: container
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

updateContainer:
  extends: .updateContainerJob
  only:
    changes:
      - Dockerfile

.buildReleaseJob:
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  stage: assemble
  variables:
    SECURE_FILES_DOWNLOAD_PATH: './'
  before_script:
    - apt-get update -qq && apt-get install -y -qq git
    - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/".insteadOf "git@gitlab.com:"
    - git submodule sync && git submodule update --init
    - chmod +x gradlew
    - "export VERSION_SHA=`echo ${CI_COMMIT_SHA:0:8}` && echo $VERSION_SHA"
    - "[ ! -d app/libs ] && mkdir app/libs"
    - 'curl -H "Authorization: Token $ORG_TOKEN" -H "Accept: application/vnd.github.v3.raw" -o app/libs/server.aar -L https://api.github.com/repos/RepoDevil/TorrServer/contents/server.aar'
    - 'curl -H "Authorization: Token $ORG_TOKEN" -H "Accept: application/vnd.github.v3.raw" -o app/libs/server-sources.jar -L https://api.github.com/repos/RepoDevil/TorrServer/contents/server-sources.jar'
    - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash

buildRelease:
  extends: .buildReleaseJob
  script:
    - ./gradlew --configure-on-demand assembleGoogleMatagi
    - cp app/build/outputs/apk/google/matagi/*.apk ./
  artifacts:
    paths:
      - Himitsu-${CI_COMMIT_SHA:0:8}-google-arm64-v8a-matagi.apk